WARNING 2019-12-05 23:56:50,666 root : 
Server в роботі :)

INFO 2019-12-05 23:56:50,666 root : Сервер доступний. Час на сервері: 2019-12-05 21:56-50
INFO 2019-12-05 23:56:50,666 root : Запитувана сторінка: : /health/
INFO 2019-12-05 23:56:50,666 root : Відповідь сервера місти наступні поля:
INFO 2019-12-05 23:56:50,666 root : Ключ: date, Значення: 2019-12-05 21:56-50
INFO 2019-12-05 23:56:50,666 root : Ключ: current_page, Значення: /health/
INFO 2019-12-05 23:56:50,666 root : Ключ: server_info, Значення: ['Linux', 'kramsayu-VirtualBox', '5.0.0-23-generic', '#24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019', 'x86_64']
INFO 2019-12-05 23:56:50,666 root : Ключ: client_info, Значення: python-requests/2.22.0
ERROR 2019-12-05 23:57:03,108 root : 
Виникла наступна помилка: 
 HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4537552f60>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2019-12-05 23:58:02,844 root : 
Виникла наступна помилка: 
 HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9168088048>: Failed to establish a new connection: [Errno 111] Connection refused'))
